# Generated by Django 4.0.3 on 2022-04-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('map_url', models.CharField(max_length=250)),
                ('img_url', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('has_sockets', models.BooleanField(default=False)),
                ('has_toilet', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('can_take_calls', models.BooleanField(default=False)),
                ('seats', models.CharField(max_length=250)),
                ('coffee_price', models.CharField(max_length=250)),
            ],
        ),
    ]
