# Generated by Django 4.0.3 on 2022-04-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='can_take_calls',
            field=models.BooleanField(choices=[(False, 'False'), (True, 'True')], default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_sockets',
            field=models.BooleanField(choices=[(False, 'False'), (True, 'True')], default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_toilet',
            field=models.BooleanField(choices=[(False, 'False'), (True, 'True')], default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_wifi',
            field=models.BooleanField(choices=[(False, 'False'), (True, 'True')], default=False),
        ),
    ]
